### PR TITLE
Added Atmospheric Pressure using Environmental Parameters PGN 130311.

### PR DESCRIPTION
**Pull request by htool**
To push environment.outside.pressure out using PGN 130311.

### CODE REVIEW

**Comment by htool** [comment]
I fail to see how the build fail is connected to my pull request.

**Comment by sbender9** [comment]
the failure is another issue, I'll fix that

**Comment by sbender9** [comment]
I think you need to also set `"Humidity Instance":  "Outside"`

**Comment by htool** [comment]
> I think you need to also set `"Humidity Instance": "Outside"`

I don't have humidity information. What makes you think it should be set?

I've got this on my can0:
2020-03-10-18:22:47.450 5 115 255 130311 Environmental Parameters:  SID = 0; Temperature Source = Sea Temperature; Humidity Source = Unknown; Temperature = 40.00 C (104.0 F); Humidity = Unknown  <-- this one is coming from a Seatalk -> SeatalkNG converter.

2020-03-10-18:22:47.606 3   7 255 130311 Environmental Parameters:  SID = Unknown; Temperature Source = Unknown; Humidity Source = Unknown; Humidity = Unknown; Atmospheric Pressure = 1.003 bar (69.2 PSI)  <-- This one is coming from this pull request. It works with my Triton2.

**Comment by sbender9** [comment]
Shoot, sorry, was think that there was a "Pressure Source"

**Pull request merged**
