### PR TITLE
feature: timeout & missing data handling, 127508

### PR DESCRIPTION
**Pull request by tkurki**
Add support for handling missing data items and defining
timeouts for individual input data items. Add 127508
support as a demo of this functionality. 127508 config
allows you to specify instance mapping from SK id to
N2K instance id.

### CODE REVIEW

**Comment by tkurki** [comment]
This was so far along that I wanted to get this shared, even if we would choose not to merge it as it is. Could you have a look and let's figure out what's the best way forward, considering that you've done overlapping stuff.

This is NOT mergeable, as I don't think missing data items are not correctly converted to N2K. What was the convention for missing/invalid field data in N2K?

**Comment by tkurki** [comment]
One question: is the idea with ` "test": "$NODE $npm_package_main"` to just check that syntax is ok?

**Comment by sbender9** [comment]
Yes,since I don't have any real tests yet. At least check the syntax.

**Comment by sbender9** [comment]
I've manually merged this into my refactor branch. Please take a look.

**Pull request closed without merging**
