### PR TITLE
feature: add support for Raymarine alarms (PGN 65288)

### PR DESCRIPTION
**Pull request by itemir**
Adds support for Raymarine alarms (i70, Raymarine buzzer, etc) for notifications.navigation.anchor and notifications.mob

### CODE REVIEW

**Comment by itemir** [comment]
See https://signalk-dev.slack.com/archives/C03F1MKQG/p1678063388755439 for discussion.

**Review by sbender9 — CHANGES_REQUESTED** [review]
I don't think you should modify the delta that comes in. Copy it or create a new from scratch.

**Comment by itemir** [comment]
Per Slack convo, pushed a change for this and existing notifications PGNs too.

**Comment by sbender9** [comment]
Please move the spelling mistake and the fuel rate change into their own PRs. They are unrelated to the original PR.

**Comment by tkurki** [comment]
Sorry, did not yet dig into this in detail, but I don't understand why conversion to N2K would (need to) create additional deltas. What's really going on here?

**Comment by sbender9** [comment]
Yeah. I don't think we need any of that in this case.

**Comment by sbender9** [comment]
@itemir i think you can remove all that logic and just send out the pgn?

**Comment by tkurki** [comment]
If we want to send a different notfication in some cases that should go in n2k-signalk. Or at least we should evaluate that.

**Comment by itemir** [comment]
I will look into this more in the weekend but here is what I see. 

Existing PGNs for notifications to NMEA2k (126983 and 126985) has this code. From what I can tell it is trying to carry some state by adding an Alert ID and some other information. Per comment 

```        //add nmea2000 alert info so that the alarm can be silenced from a NMEA source```

Idea is to use that to silence it from NMEA. Not sure about the mechanics of this. Then [`n2k-plugin` recognizes this](https://github.com/SignalK/n2k-signalk/blob/4b56bf44800df7e36b6b0a1bc3dea43b131caf0f/pgns/126983.js#L39) which I presume, is keying the same Alert ID and other fields coming back from NMEA2000 upon a hypothetical suppress/silence operation on a NMEA 2000 device. How is this supposed to silence an alarm is not clear to me.

I can change my code to ignore all of this though existing notifications PGNs need a look. This is a almost a multi stage workflow (Notification generated on Signal K -> Notification pushed to N2k -> Notification silenced on a N2k device -> That message gets back to Signal K -> Then what happens?). I am not sure if this is doing that right now or is some remnant code that no-one really investigated.

**Comment by itemir** [comment]
Ok, pushed new changes to remove publishing deltas. The plugin still needs some basic state as I explained in the commit,     consider these two scenarios:

1. A Signal K notification goes on (e.g. anchor alarm) and then off when the boat swings back into a safe anchor radius. We want the alarm on NMEA 2k
    silence automatically.

2. A Signal K notification goes on (e.g. anchor alarm) and then another goes on (e.g. MOB) and boat swings back into a safe anchor radius. We want the first alarm to silence but we want the MOB alarm to continue.

(1) and (2) together require some state keeping to differentiate the alarms. alertId was handling the need for this state. The refactor uses notification path for that state. This means we cannot keep state across two alarms on the same path (e.g. two anchor alarms or two MOBs) but we can keep state across different alarm types, which is the critical one.

I removed the changes for `notifications.js`. It needs a separate look since it has some embedded logic in it I cannot trace. I don't have a device that handles regular notifications so I can only test the Raymarine alarms and PGNs. Raymarine alarming works on my network on numerous devices (i70, buzzer, etc) with the stateful logic explained above.

**Pull request merged**
